[project]
name = "butter"
version = "0.0.1"
description = "An template for desktop test sequencing apps with web based GUIs and a Python backend."
authors = [{ name = "James Shull", email = "james.shull@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9, <3.13"
dependencies = [
    "pillow>=10.4.0",
    "pyserial>=3.5",
    "pyvisa>=1.14.1",
    "requests>=2.32.3",
    "starlette>=0.38.5",
    "uvicorn>=0.30.6",
    "pythonnet>=3.0.4",
    "keyring>=25.4.1",
    "ft4222>=1.10.0",
    "pywin32>=306; sys_platform == 'win32'",
    "psutil>=6.0.0",
    "pyodbc>=5.1.0",
    "zebra>=0.1.0",
    "sse-starlette>=2.1.3",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.3",
    "selenium>=4.25.0",
    "webdriver-manager>=4.0.2",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.36",
    "mkdocstrings[python]>=0.26.1",
]
dev = [
    "ruff",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint]
# Enable Pyflakes, pycodestyle, isort
select = ["E", "F", "I"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
